### ISSUE TITLE
Acceleration build with APT-FAST

### ISSUE THREAD

**Issue by urpylka** [CopterExpress/clever#19]
Installation of packages with apt (apt-get) in one stream takes an essential part of the build time. What do you think about using **apt-fast** utility? https://github.com/ilikenwf/apt-fast
```bash
sudo alias apt-get='apt-fast'
```

**Comment by korigod** [comment]
`apt-fast` uses `axel` to download packages from multiple mirrors. We can just set up a local debian mirror instead, it's just several hundreds of gigabytes for all packages (https://www.debian.org/mirror/size). This way we will not depend on our internet connection at all.

**Comment by urpylka** [comment]
Ok, we made decision, that we don't use apt-fast.
---
Also we made local mirror with debian packages. Our scripts avaible in our [private repo](https://github.com/CopterExpress/coex-mirror).
