### ISSUE TITLE
Будет ли работать образ/пи с arducopter

### ISSUE THREAD

**Issue by whoim2** [CopterExpress/clever#203]
Будет ли работать образ/пи с arducopter на чибиос для F4, например на омнибас?

https://firmware.ardupilot.org/Copter/latest/omnibusf4pro/

Если не все будет работать, то что именно нет? Пока нет px4 в доступе

**Comment by okalachev** [comment]
ChibiOS здесь не играет особой роли. Если говорить о поддержке ArduCopter, то в mavros (модуле для проброса MAVLink в ROS) есть его поддержка, то есть связь с полетным контроллером работать будет. Все остальные модули, специфичные для Клевера, не тестируются с ArduCopter. Если что-то и будет работать, то наверняка только частично.

`simple_offboard` не заведется: он заточен под режим `OFFBOARD` в PX4.

**Comment by whoim2** [comment]
Спасибо, отложу тогда до появления пикса в арсенале
