### ISSUE TITLE
Use raspi-config for configure hardware interfaces

### ISSUE THREAD

**Issue by urpylka** [CopterExpress/clever#38]
Now we used [forked scripts](
https://github.com/CopterExpress/clever/blob/v0.4/image_builder/scripts/hardware_setup.sh) from [`raspi-config`](https://github.com/RPi-Distro/raspi-config) for configure hardware interfaces.

I propose used `raspi-config`. F.e. `/usr/bin/raspi-config nonint do_i2c 0`.

**Comment by urpylka** [comment]
I replaced our forked-scripts to ‘raspi-config’ https://github.com/CopterExpress/clever/commit/0346c48546590faa00f7ee0a1d0ea71f6343bd17

But I meet problem with lock version of raspi-config.
F.e. I know code (to enable only hardware uart, wo console) that I wanted to use, added to ‘raspi-config’ only 4 days ago.

I propose several solutions:
1. Add ‘raspi-config’ as submodule to repository
2. Add execute file of ‘raspi-config’ to this repository as file
3. Replace ‘raspi-config’ in repo to fixed version

**Comment by urpylka** [comment]
Also I found bug in log of `image_builder`. So in `chroot` doesn't work `dtparam` util.

**Comment by andrew-xdn** [comment]
Your "config" directory has a really strange location. I thing the right place for it is in "/sys/kernel", not in root. Are you sure you run "dtparam" in the correct environment? Still, I think it's not ok to run utility that use kernel or hardware resources under chroot. Isn't it better to edit "/boot/config.txt" directly in this case?

**Comment by urpylka** [comment]
@andrew-xdn I checked environment, it's normal.
And `raspi-config` change `/boot/config.txt`, but also trying use dynamic modules. I don't mind that normal run kernel-utility in chroot. 

Because temporarily I made hack in PR https://github.com/CopterExpress/clever/pull/42. Let's discuss!

**Comment by urpylka** [comment]
I found solution how we can enable HW UART interface wo user console with current version of `raspi-config` in non-interactive mode. More there https://github.com/CopterExpress/clever/pull/43.

Now we haven't problems with lock version of `raspi-config`.

**Comment by urpylka** [comment]
Now we use RPi init script w raspi-config https://github.com/CopterExpress/clever/pull/68
