### ISSUE TITLE
Проблема при подключении Raspberry 3 к PX4 по UART

### ISSUE THREAD

**Issue by asdfg171** [CopterExpress/clever#41]
Не передаются данные при подключении Raspberry 3 к PX4 по UART, хотя в launch файле Clever тип подключения установлен на "uart" и передача по UART включена.
При подключении по USB данные передаются. 
Подскажите, пожалуйта, в чем может быть проблема?

**Comment by urpylka** [comment]
Добрый день, отключен аппаратный uart, скоро добавим поддержку чтобы работал «из коробки».

Для решения проблемы сейчас, наберите ‘sudo raspi-config’
Затем зайдите в разлел интерфейсы, выключите консоль на UART и включите сам аппаратный интерфейс.
