### ISSUE TITLE
Проблема с переходом в режим "OFFBOARD"

### ISSUE THREAD

**Issue by asdfg171** [CopterExpress/clever#44]
Добрый день!

Не получается перейти в полетный режим "OFFBOARD".
Команда `rosservice call /mavros/set_mode "base_mode: 0 custom_mode: 'OFFBOARD'"` возвращает False.
Возможно, в прошивке PX4 нет такого режима.
Подскажите, пожалуйста, как перейти в данный режим?

**Comment by okalachev** [comment]
PX4 нельзя перевести в `OFFBOARD`, если не шлется поток setpoint'ов, то есть целевого задания для полета. В образе включен модуль, для упрощенного программирования автономных полетов, который автоматически правильно переводит в `OFFBOARD`: https://clever.copterexpress.com/simple_offboard.html.

При этом, если `mode_sent` возращается как `False`, то необходимо проверить подключение коптера (`rostopic echo /mavros/state`). При необходимости сменить тип подключения с USB на  UART или наоборот.

**Comment by okalachev** [comment]
В PX4 нет режимов  `STABILIZE` и `ALT_HOLD` (есть `STABILIZED` и `ALTCTL`).

У тебя точно PX4? Может, APM?

**Comment by asdfg171** [comment]
Спасибо, после перепрошивки PX4 все работает, в режим 'OFFBOARD' переходит.
