### ISSUE TITLE
Добавлять имя коптера в файл /etc/hostname

### ISSUE THREAD

**Issue by urpylka** [CopterExpress/clever#46]
Сегодня поменял эту штуку, очень стало удобно, если несколько дронов подключены к одной точке доступа (отображается что за дрон). Также в терминале пишет сразу понятно, где ты работаешь.

Предложение писать именно уникальный id, чтобы можно было понять что за дрон. Делать это лучше так https://github.com/urpylka/raspberrypi/blob/master/configuration/setup_pi_interactive#L37

**Comment by urpylka** [comment]
Что думаете? @okalachev @korigod

**Comment by korigod** [comment]
Давай, это нормально.

**Comment by urpylka** [comment]
Я единственное боюсь что это может поломать доступ по `clever`

**Comment by sfalexrog** [comment]
Добавлено в https://github.com/CopterExpress/clever/commit/75199586983e75840f8fb8cf728494dc46a5d3d4 и https://github.com/CopterExpress/clever/commit/1d591965a3d38dacbd273058b70b2cafd1d8a294. В результате есть скрипт `clever_rename`, который принимает единственный параметр - новый hostname - и довольно тупо его выставляет во всех нужных местах; при этом на ssid это не влияет, просто при первом запуске этот скрипт вызывается с новым ssid.

**Comment by korigod** [comment]
Спасибо!
