### ISSUE TITLE
bcm2835-aux-uart 3f215040.serial: could not get clk: -517

### ISSUE THREAD

**Issue by urpylka** [CopterExpress/clever#55]
bcm2835-aux-uart 3f215040.serial: could not get clk: -517
https://www.raspberrypi.org/forums/viewtopic.php?t=195974
https://github.com/raspberrypi/linux/issues/1913

**Comment by korigod** [comment]
Видимо, была как-то такая проблема, но не повторялась. Если повторится, переоткроем.
