### ISSUE TITLE
Проблема с жестко заданным портом подключения PixHawk to Raspberry

### ISSUE THREAD

**Issue by yudzhi** [CopterExpress/clever#66]
В mavros.launch порт подключения PixHawk жестко прописан как ttyACM0:
` <param name="fcu_url" value="/dev/ttyACM0" if="$(eval fcu_conn == 'usb')"/>`
При подключении к Raspberry более одного внешнего устройства (USB, UART) - в частности, MarvelMind - могут возникать сбои, так как PixHawk далеко не всегда оказывается висящим на нулевом порту.

**Comment by okalachev** [comment]
Надо понять, всегда ли пикс именован одним способом в `serial/by-id`. Зависит ли это от типа прошивки, модели пикса и т. д.

**Comment by okalachev** [comment]
Теперь подключение осуществляется через udev-правила.
