### ISSUE TITLE
Bug with import module rospy

### ISSUE THREAD

**Issue by xsestech** [CopterExpress/clever#69]
When I started app I had this errors
  import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 5, in <module>
    import genpy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File `"/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py",` line 44, in <module>
    import yaml
This is my code

```
# -*- coding: utf-8 -*-
import rospy
from clever import srv
from std_srvs.srv import Trigger
import rospy
from clever import srv
from std_srvs.srv import Trigger

rospy.init_node('xopter')   # название вашей ROS-ноды

# Создаем прокси ко всем сервисам:

get_telemetry = rospy.ServiceProxy('get_telemetry', srv.GetTelemetry)
navigate = rospy.ServiceProxy('navigate', srv.Navigate)
navigate_global = rospy.ServiceProxy('navigate_global', srv.NavigateGlobal)
set_position = rospy.ServiceProxy('set_position', srv.SetPosition)
set_velocity = rospy.ServiceProxy('set_velocity', srv.SetVelocity)
set_attitude = rospy.ServiceProxy('set_attitude', srv.SetAttitude)
set_rates = rospy.ServiceProxy('set_rates', srv.SetRates)
land = rospy.ServiceProxy('land', Trigger)
release = rospy.ServiceProxy('release', Trigger)
z = 1  # высота
tolerance = 0.2  # точность проверки высоты (м)

# Запоминаем изначальную точку
start = get_telemetry()

# Взлетаем на 2 м
print(navigate(z=z, speed=0.5, frame_id='fcu_horiz', auto_arm=True))

# Ожидаем взлета
while True:
    # Проверяем текущую высоту
    if get_telemetry().z - start.z + z < tolerance:
        # Взлет завершен
        break
    rospy.sleep(5)
res = land()
if res.success:
    print("Copter is landing")
```

**Comment by urpylka** [comment]
What is your image version?

It’s like as error when you haven’t ros enviroment. Use: /opt/ros/kinetic/setup.bash

**Comment by okalachev** [comment]
What is the image version?
@urpylka

**Comment by xsestech** [comment]
![code](https://user-images.githubusercontent.com/29453203/46655264-c5a04680-cbb3-11e8-98e5-5f6ed2306d59.png)

**Comment by xsestech** [comment]
> What is the image version?
> @urpylka

![code](https://user-images.githubusercontent.com/29453203/46655287-dc469d80-cbb3-11e8-94ce-d4f3ee647259.png)

**Comment by urpylka** [comment]
All clever-images (see releases on github) have a version. Use `cat /etc/clever_release` for see that

**Comment by urpylka** [comment]
Or you use clever (ros package) without image? @xsestech

**Comment by xsestech** [comment]
> /opt/ros/kinetic/setup.bash

I had error : 
 /opt/ros/kinetic/setup.bash: command not found

**Comment by xsestech** [comment]
I am using image from official site.

**Comment by xsestech** [comment]
> What is your image version?
> 
> It’s like as error when you haven’t ros enviroment. Use: /opt/ros/kinetic/setup.bash

I had an error:
sudo: /opt/ros/kinetic/setup.bash: command not found

**Comment by urpylka** [comment]
I can not help you if you don’t give me more information.

**Comment by xsestech** [comment]
I coppied image from  https://github.com/CopterExpress/clever/releases to cd card and connected by ssh to rasberry pi and wrote this  python script.
![2018-10-09 14_42_36](https://user-images.githubusercontent.com/29453203/46667234-b03a1500-cbd1-11e8-8584-2b764efb44ee.png) and had this output
![2018-10-09 14_42_54](https://user-images.githubusercontent.com/29453203/46667280-d8c20f00-cbd1-11e8-9eed-452cddf6d039.png)

**Comment by urpylka** [comment]
Error w command not found says that you haven’t ROS on your image. Please before use our image read documentation on gitbook. Or use our preconfigured **clever-image** (you can download it in releases on gh)

**Comment by xsestech** [comment]
I downloaded clever-image from releases from github

**Comment by urpylka** [comment]
That’s better. Next say me your image version. Execute `cat /etc/clever_version` on your image.

**Comment by xsestech** [comment]
v0.11.4

**Comment by urpylka** [comment]
Great 👍 The problem was caused because this image is not tested. Use image with `Latest release` label. For example v0.8.1

**Comment by xsestech** [comment]
Thanks

**Comment by urpylka** [comment]
I guess that is new stable version will be created on next week

**Comment by xsestech** [comment]
Ok
