### ISSUE TITLE
Запуск дальномера

### ISSUE THREAD

**Issue by copterspace** [CopterExpress/clever#82]
Коллеги, что-то не завёлся дальномер VL53L1X на образе 13-го Клевера.
Скачал образ. В raspi-config разрешил i2c, больше ничего не настраивал.
Подключать i2c пробовали и к 0 и к 1 каналу, фотки ниже.
![img_20181116_155734](https://user-images.githubusercontent.com/38784273/48621113-f39b5680-e9bb-11e8-8262-8f4573ae094c.jpg)
![img_20181116_160225](https://user-images.githubusercontent.com/38784273/48621114-f433ed00-e9bb-11e8-911f-96d2bceb2a57.jpg)

Остановил clever, просто пытаюсь запустить ноду дальномера (python vl53l1x.py)

После стр 26:
tof = VL53L1X.VL53L1X(i2c_bus=1, i2c_address=0x29)
tof.open() # Initialise the i2c bus and configure the sensor

Куча ошибок, в стиле: 
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/VL53L1X.py", line 99, in _i2c_read
    self._i2c.i2c_rdwr(msg_w, msg_r)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 483, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
IOError: [Errno 121] Remote I/O error

Просьба поделиться правильной схемой подключения дальномера, что-то не нашёл ничего внятного в сети.

**Comment by okalachev** [comment]
У нас немного другая платка с лазером: https://ru.aliexpress.com/item/VL53L0X-Time-of-Flight-ToF-Laser-Ranging-Sensor-Breakout-940nm-GY-VL53L0XV2-Laser-Distance-Module-I2C/32773306734.html.

Я просто воткнул SDA/SCL в соответствующие пины на Raspberry и VCC/GND в питание (3.3) по этому пинауту: https://hackster.imgix.net/uploads/image/file/48843/RP2_Pinout.png?auto=compress%2Cformat&w=1280&h=960&fit=max.

Как-нибудь позже нарисую хрему подключения в инструкцию.

А когда clever запускается как сервис лазер точно не работает? Возможно эта нода требует рута.

**Comment by copterspace** [comment]
Раскопал в чём дело. Спасибо за ссылку на ваш дальномер, она помогла.
Мой дальномер по умолчанию работал в другом режиме (PWM/uart). Надо было перевести его в режим i2c, замкнув PS на GND. После этого всё заработало.
Рут не требовался (и не требуется).
Когда НЕ работал дальномер - в топике почему-то всё равно появлялось расстояние 1.75 метра (при запущенном clever, я не разбирался, откуда). После того как перемычку замкнул - дальномер заработал, продолжим испытания.
